version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      restaurant_network:
        ipv4_address: 10.5.0.2
  
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      restaurant_network:
        ipv4_address: 10.5.0.3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://10.5.0.3:29092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://10.5.0.3:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "restaurant_topic:1:1"
  restaurant:
    image: restaurant
    build: ../kotlin-spring-boot-restaurant/.
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8080:8080
    networks:
      - restaurant_network
  kitchen:
    image: kitchen
    build: ../kotlin-spring-boot-kitchen/.
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8080
    networks:
      - restaurant_network
networks:
  restaurant_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1